#!/bin/sh
files="create-pebble-project pebble-build-run pebble-start-logging start-pebble-server"

mkdir -p src/osx

cd osx
for file in $files; do
  echo $file
  cp $file ../src/osx
done

cd ../
ls -l src/osx
git add src
git commit -a
git push

cd src/osx
rm -rf *
cd ..
rmdir osx
cd ../
rmdir src


